# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
