# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20160414_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
